Update README.md
actions-on-packages/.github pull request #2
Opened 2022-11-14 11:52 UTC by aditsrin

Update getting started guidelines with the latest changes

2022-11-16 11:36 UTC, vinaykanamarlapudi commented on README.md
> +- After adding of release.yml file into, a user can create packages for their action repo and publish them to GHCR by creating releases with some conditions on the `gitTag` used.
Can be reframed as : After adding release.yml, action packages can be created and published to GHCR by following the normal release procedure either using Repo Releases GUI or CLI.

2022-11-16 11:36 UTC, vinaykanamarlapudi commented on README.md
> +- The `gitTag` used for release creation should follow the guidlines of being semver compliant as mentioned in the release creation page. User should follow these guidlines :
Can be reframed as "The `gitTag` used for release creation should follow the guidlines of being semver compliant as mentioned in the release creation page. Refer below screenshot"

2022-11-16 11:37 UTC, vinaykanamarlapudi commented on README.md
> +- Tags that strictly follow semantic versioning(`1.0.0` or `2.3.0`) or tags that have a prefix `v` along with semantic versioned tags(`v1.0.0` or `v2.3.0`) are acceptable (packages cannot be re-publi
Can add this as seperate sentence rather in brackets

2022-11-16 11:37 UTC, vinaykanamarlapudi requested changes
Added few comments

2022-11-16 11:47 UTC, aditsrin commented on README.md
> +- After adding of release.yml file into, a user can create packages for their action repo and publish them to GHCR by creating releases with some conditions on the `gitTag` used.
Done.

2022-11-16 11:47 UTC, aditsrin commented on README.md
> +- The `gitTag` used for release creation should follow the guidlines of being semver compliant as mentioned in the release creation page. User should follow these guidlines :
Done.

2022-11-16 11:47 UTC, aditsrin commented on README.md
> +- Tags that strictly follow semantic versioning(`1.0.0` or `2.3.0`) or tags that have a prefix `v` along with semantic versioned tags(`v1.0.0` or `v2.3.0`) are acceptable (packages cannot be re-publi
Done.

2022-11-16 12:19 UTC, vinaykanamarlapudi commented on README.md
> +- This release.yml is executed when a release is created either through GUI or CLI. Then the user has to track progress of package publishing from the workflow run of this release.yml
Can be reframed as "Release.yml workflow is triggered when a release is created either through Releases GUI or CLI. The progress of package publishing can be tracked from the workflow run of the release.yml

2022-11-16 12:22 UTC, vinaykanamarlapudi commented on README.md
> +- Packages cannot be re-published with existing package tags again.
Reframed as "As the actions on packages are immutable, packages with existing semver tag once published, they cannot be republished" . 

Check if the above statement is adding more clarity

2022-11-18 14:02 UTC, vinaykanamarlapudi approved these changes

2022-11-20 17:05 UTC, merged